### ISSUE TITLE
Link suggestion

### ISSUE THREAD

**Issue by merewif** [openoms/bitcoin_magyarul#2]
There is a link in README.md

> Murray N. Rothbard - Mit művelt a kormány a pénzünkkel?https://mises-media.s3.amazonaws.com/What%20Has%20Government%20Done%20to%20Our%20Money%20%E2%80%94%20Hungarian%20translation.pdf

Which I'd suggest changing to

> https://d206501ssxmwto.cloudfront.net/wp-content/uploads/2017/12/Murray-N.-Rothbard-Mit-muvelt-a-kormany-a-penzunkkel5.pdf

for the Mises Institue version has been improved and issues were fixed for readability .

>

**Comment by openoms** [comment]
Thank you for the suggestion. I like it that the Mises Institute / Ellenpropaganda watermark has been removed. One should not be forced to read these words on the bottom of every page. Will change the link now.
If you fork the repository for yourself I am very happy to have pull requests for additions or modifications.
